version: "3.8"

services:

  #DATABASE
  database:
    container_name: database_avaliai
    image: postgres:14.1
    networks:
      - avaliai_net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_avaliai:/var/lib/postgresql
      - database_avaliai_data:/var/lib/postgresql/data


networks:
  avaliai_net:

volumes:
  database_avaliai:
  database_avaliai_data:
  rabbitmq_avaliai_vol:

