version: "3.7"

services:

  #DATABASE
  avaliai:
    container_name: avaliai
    image: postgres:12.6
    networks:
      - avaliai_net
    ports:
      - "5453:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PstD2a5DA4fUvgXEEXX
      POSTGRES_DB: avaliai
    volumes:
      - database_avaliai:/var/lib/postgresql
      - database_avaliai_data:/var/lib/postgresql/data

networks:
  avaliai_net:

volumes:
  database_avaliai:
  database_avaliai_data:
  rabbitmq_avaliai_vol:

