name: Build and Test commits
on:
  pull_request:
    branches:
      - develop

jobs:
  pipeline:
    runs-on: ubuntu-latest # Os comandos serão executados em um sistema operacional Linux

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          for commit in $(git rev-list ${{ github.event.before}}..${{ github.sha}}); do
              git checkout $commit
              echo "run test"
          done

      - name: Set up JDK 17
        uses: actions/setup-java@v1 # Configura o Java 1.8
        with:
          java-version: 17

      - name: Build
        working-directory: "codigo/backend/avaliai"
        run: mvn package -Dmaven.test.skip=true # Compila o código fonte

      - name: Unit Test
        working-directory: "codigo/backend/avaliai"
        run: mvn test # Executada os testes de unidade
