name: Github CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  pipeline:
    runs-on: ubuntu-latest # Os comandos serão executados em um sistema operacional Linux

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2 # Faz o checkout do código recebido

      - name: Set up JDK 17
        uses: actions/setup-java@v1 # Configura o Java 1.8
        with:
          java-version: 17
          path: "codigo/backend/avaliai"

      - name: Build
        run: mvn package -Dmaven.test.skip=true # Compila o código fonte

      - name: Unit Test
        run: mvn test # Executada os testes de unidade
